version: "3.8"

services:

  #################################
  # AMQP: The RabbitMQ microservice
  #################################
  rabbitmq:
    build:
      context: ./amqp
      dockerfile: Dockerfile
    image: mondo/amqp
    restart: always
    ports: [5672:5672, 15672:15672, 15674:15674, 61613:61613]

  setup:
    build:
      context: ./amqp
      dockerfile: setup.Dockerfile
    depends_on:
      - rabbitmq

