services:
  pharmacy:
    build: .
    image: ESDG2T1/pharmacy:1.0
    restart: always
    ports:
      - "5004:5004"
    environment:
      INVENTORY_API_BASE_URL: "https://personal-dxi3ngjv.outsystemscloud.com/Inventory/rest/v1"
      PRESCRIPTION_SERVICE_URL: "http://prescription:5002"
    networks:
      - pharmacy_network
      - atomic_network

networks:
  pharmacy_network:
    driver: bridge
  atomic_network:
    external: true
    name: atomic_network
