services:

  #################################
  # Patient Microservice
  #################################
  patient:
    build: ./Patient/patient
    image: ESDG2T1/patient:1.0
    restart: always
    ports: [5001:5001]
    depends_on:
      - patient_db
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/patientdb

  #################################
  # Patient SQL Database
  #################################
  patient_db:
    image: mysql:latest
    restart: always
    ports: [ 3301:3306 ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./Patient/db/patient.sql:/docker-entrypoint-initdb.d/init.sql

  #################################
  # Appointment Microservice
  #################################
  appointment:
    build: ./Appointment/appointment
    image: ESDG2T1/appointment:1.0
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - appointment_db
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/appointmentdb

  #################################
  # Appointment SQL Database
  #################################
  appointment_db:
    image: mysql:latest
    restart: always
    ports:
      - "3302:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./Appointment/db/appointment.sql:/docker-entrypoint-initdb.d/init.sql

  #################################
  # Prescription Microservice
  #################################
  prescription:
    build: ./Prescription/prescription
    image: ESDG2T1/prescription:1.0
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      - prescription_db
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/prescriptiondb

  #################################
  # Prescription SQL Database
  #################################
  prescription_db:
    image: mysql:latest
    restart: always
    ports:
      - "3303:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./Prescription/db/prescription.sql:/docker-entrypoint-initdb.d/init.sql
