version: "3.8"

services:

  # Simple microservice

  #################################
  # Patient: The Patient microservice
  #################################

  patient:
    build: ./Patients/patient
    image: ESDT8/patient:1.0
    # container_name: patient_microservice
    restart: always
    ports: [ 5001:5000 ]
    depends_on:
      - patient_db
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3301/patientdb

  #################################
  # Patient SQL Database
  #################################
  patient_db:
    image: mysql:latest
    restart: always
    ports: [ 3301:3306 ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./Patients/db/patient.sql:/docker-entrypoint-initdb.d/init.sql